name = "FiniteDifferenceSC"
uuid = "1a638cd3-6398-40ca-a8a0-884cfede8f0d"
authors = ["S.C."]
version = "1.0.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
