name = "FiniteDifferenceSC"
uuid = "1a638cd3-6398-40ca-a8a0-884cfede8f0d"
version = "1.0.0"
authors = ["S.C."]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
